package io.taucoin.android.wallet.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import io.taucoin.android.wallet.db.entity.BlockInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BLOCK_INFO".
*/
public class BlockInfoDao extends AbstractDao<BlockInfo, Long> {

    public static final String TABLENAME = "BLOCK_INFO";

    /**
     * Properties of entity BlockInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BlockHeight = new Property(1, int.class, "blockHeight", false, "BLOCK_HEIGHT");
        public final static Property BlockSync = new Property(2, int.class, "blockSync", false, "BLOCK_SYNC");
        public final static Property AvgIncome = new Property(3, String.class, "avgIncome", false, "AVG_INCOME");
        public final static Property MedianFee = new Property(4, String.class, "medianFee", false, "MEDIAN_FEE");
        public final static Property MinerNo = new Property(5, String.class, "minerNo", false, "MINER_NO");
    }


    public BlockInfoDao(DaoConfig config) {
        super(config);
    }
    
    public BlockInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BLOCK_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"BLOCK_HEIGHT\" INTEGER NOT NULL ," + // 1: blockHeight
                "\"BLOCK_SYNC\" INTEGER NOT NULL ," + // 2: blockSync
                "\"AVG_INCOME\" TEXT," + // 3: avgIncome
                "\"MEDIAN_FEE\" TEXT," + // 4: medianFee
                "\"MINER_NO\" TEXT);"); // 5: minerNo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BLOCK_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BlockInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getBlockHeight());
        stmt.bindLong(3, entity.getBlockSync());
 
        String avgIncome = entity.getAvgIncome();
        if (avgIncome != null) {
            stmt.bindString(4, avgIncome);
        }
 
        String medianFee = entity.getMedianFee();
        if (medianFee != null) {
            stmt.bindString(5, medianFee);
        }
 
        String minerNo = entity.getMinerNo();
        if (minerNo != null) {
            stmt.bindString(6, minerNo);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BlockInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getBlockHeight());
        stmt.bindLong(3, entity.getBlockSync());
 
        String avgIncome = entity.getAvgIncome();
        if (avgIncome != null) {
            stmt.bindString(4, avgIncome);
        }
 
        String medianFee = entity.getMedianFee();
        if (medianFee != null) {
            stmt.bindString(5, medianFee);
        }
 
        String minerNo = entity.getMinerNo();
        if (minerNo != null) {
            stmt.bindString(6, minerNo);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BlockInfo readEntity(Cursor cursor, int offset) {
        BlockInfo entity = new BlockInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // blockHeight
            cursor.getInt(offset + 2), // blockSync
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // avgIncome
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // medianFee
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // minerNo
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BlockInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBlockHeight(cursor.getInt(offset + 1));
        entity.setBlockSync(cursor.getInt(offset + 2));
        entity.setAvgIncome(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMedianFee(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMinerNo(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BlockInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BlockInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BlockInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
