package io.taucoin.android.wallet.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import io.taucoin.android.wallet.db.entity.IncreasePower;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INCREASE_POWER".
*/
public class IncreasePowerDao extends AbstractDao<IncreasePower, Long> {

    public static final String TABLENAME = "INCREASE_POWER";

    /**
     * Properties of entity IncreasePower.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Address = new Property(1, String.class, "address", false, "ADDRESS");
        public final static Property Budget = new Property(2, String.class, "budget", false, "BUDGET");
        public final static Property Fee = new Property(3, String.class, "fee", false, "FEE");
        public final static Property Consume = new Property(4, long.class, "consume", false, "CONSUME");
        public final static Property Count = new Property(5, long.class, "count", false, "COUNT");
    }


    public IncreasePowerDao(DaoConfig config) {
        super(config);
    }
    
    public IncreasePowerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INCREASE_POWER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ADDRESS\" TEXT," + // 1: address
                "\"BUDGET\" TEXT," + // 2: budget
                "\"FEE\" TEXT," + // 3: fee
                "\"CONSUME\" INTEGER NOT NULL ," + // 4: consume
                "\"COUNT\" INTEGER NOT NULL );"); // 5: count
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INCREASE_POWER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, IncreasePower entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(2, address);
        }
 
        String budget = entity.getBudget();
        if (budget != null) {
            stmt.bindString(3, budget);
        }
 
        String fee = entity.getFee();
        if (fee != null) {
            stmt.bindString(4, fee);
        }
        stmt.bindLong(5, entity.getConsume());
        stmt.bindLong(6, entity.getCount());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, IncreasePower entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(2, address);
        }
 
        String budget = entity.getBudget();
        if (budget != null) {
            stmt.bindString(3, budget);
        }
 
        String fee = entity.getFee();
        if (fee != null) {
            stmt.bindString(4, fee);
        }
        stmt.bindLong(5, entity.getConsume());
        stmt.bindLong(6, entity.getCount());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public IncreasePower readEntity(Cursor cursor, int offset) {
        IncreasePower entity = new IncreasePower( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // address
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // budget
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // fee
            cursor.getLong(offset + 4), // consume
            cursor.getLong(offset + 5) // count
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, IncreasePower entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAddress(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBudget(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFee(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setConsume(cursor.getLong(offset + 4));
        entity.setCount(cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(IncreasePower entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(IncreasePower entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(IncreasePower entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
