package io.taucoin.android.wallet.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import io.taucoin.android.wallet.db.entity.MiningReward;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MINING_REWARD".
*/
public class MiningRewardDao extends AbstractDao<MiningReward, Long> {

    public static final String TABLENAME = "MINING_REWARD";

    /**
     * Properties of entity MiningReward.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Address = new Property(1, String.class, "address", false, "ADDRESS");
        public final static Property TxHash = new Property(2, String.class, "txHash", false, "TX_HASH");
        public final static Property MinerFee = new Property(3, long.class, "minerFee", false, "MINER_FEE");
        public final static Property PartFee = new Property(4, long.class, "partFee", false, "PART_FEE");
        public final static Property Time = new Property(5, String.class, "time", false, "TIME");
        public final static Property BlockHash = new Property(6, String.class, "blockHash", false, "BLOCK_HASH");
        public final static Property Valid = new Property(7, int.class, "valid", false, "VALID");
    }


    public MiningRewardDao(DaoConfig config) {
        super(config);
    }
    
    public MiningRewardDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MINING_REWARD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ADDRESS\" TEXT," + // 1: address
                "\"TX_HASH\" TEXT," + // 2: txHash
                "\"MINER_FEE\" INTEGER NOT NULL ," + // 3: minerFee
                "\"PART_FEE\" INTEGER NOT NULL ," + // 4: partFee
                "\"TIME\" TEXT," + // 5: time
                "\"BLOCK_HASH\" TEXT," + // 6: blockHash
                "\"VALID\" INTEGER NOT NULL );"); // 7: valid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MINING_REWARD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MiningReward entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(2, address);
        }
 
        String txHash = entity.getTxHash();
        if (txHash != null) {
            stmt.bindString(3, txHash);
        }
        stmt.bindLong(4, entity.getMinerFee());
        stmt.bindLong(5, entity.getPartFee());
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        String blockHash = entity.getBlockHash();
        if (blockHash != null) {
            stmt.bindString(7, blockHash);
        }
        stmt.bindLong(8, entity.getValid());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MiningReward entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(2, address);
        }
 
        String txHash = entity.getTxHash();
        if (txHash != null) {
            stmt.bindString(3, txHash);
        }
        stmt.bindLong(4, entity.getMinerFee());
        stmt.bindLong(5, entity.getPartFee());
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        String blockHash = entity.getBlockHash();
        if (blockHash != null) {
            stmt.bindString(7, blockHash);
        }
        stmt.bindLong(8, entity.getValid());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MiningReward readEntity(Cursor cursor, int offset) {
        MiningReward entity = new MiningReward( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // address
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // txHash
            cursor.getLong(offset + 3), // minerFee
            cursor.getLong(offset + 4), // partFee
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // time
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // blockHash
            cursor.getInt(offset + 7) // valid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MiningReward entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAddress(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTxHash(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMinerFee(cursor.getLong(offset + 3));
        entity.setPartFee(cursor.getLong(offset + 4));
        entity.setTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBlockHash(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setValid(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MiningReward entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MiningReward entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MiningReward entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
